org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3-snapshot-8
loader_version=0.19.3
loom_version=1.17.19
kotlin_version=2.4.10
fabric_kotlin_version=1.13.13+kotlin.2.4.10
lwjgl_version=3.4.1
serialization_version=1.11.0

mod_version=0.10-fabric-26.3-snapshot-8
maven_group=io.github.micheanl
archives_base_name=libgltf
fabric_api_version=0.157.1+26.3
