name: publish renderapi to central

"on":
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout renderapi
        uses: actions/checkout@v6
        with:
          repository: RenderShard/renderapi
          ref: v0.11-fabric-26.3-snapshot-8
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "microsoft"
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish to maven central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
        run: ./gradlew build publishAggregationToCentralPortal
